######################################################################
# Automatically generated by qmake (3.0) Mon Jan 5 18:38:30 2015
######################################################################

TEMPLATE = app
TARGET = Server
INCLUDEPATH += .

# Input
SOURCES += server.c
